env:
  browser: true
  commonjs: true
  es2021: true
  jest: true
extends:
  - standard
parserOptions:
  ecmaVersion: latest
plugins:
  - jest
  - standard
  - mocha
  - chai
  - node
  - promise
  - import
  
  
rules: {}
overrides:
  - files:
      - "**/*.test.js"
      - "**/*.spec.js"
    excludedFiles:
      - "*.temp.js"
globals:
  dbHandler: true
  before: true
    
    
