repos:
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.1.0  # Use the latest stable version
  hooks:
  - id: detect-secrets
    args: ['--baseline', '.secrets.baseline']  # Optional baseline for known secrets
